import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import Crad from "../components/card";
import styles from "../styles/Home.module.css";
import { fectchCoffeSTores } from "../lib/coffeSore";
import { useEffect } from "react";
import axios from "axios";
import StoresList from "../components/storesList";
import { useTrackLocation } from "../hooks/use-track-location";
import { useDispatch, useSelector } from "react-redux";
import { setLatLong, getCoffeeStores } from "../redux/coffeeStoreSlice";

export async function getStaticProps(context) {
  const coffeeStores = await fectchCoffeSTores();
  return {
    props: {
      coffeeStores,
    }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  // const [coffeeStores, setCoffeStores] = useState("");

  const latLong = useSelector((state) => state.coffeeStore.latLong);
  const coffeeStoresData = useSelector(
    (state) => state.coffeeStore.coffeeStoresData
  );

  const dispatch = useDispatch();

  //Custom hook
  const { tracLocationHandler, locationErrMsg, loading } = useTrackLocation();

  useEffect(async () => {
    const fetchedStores = await fectchCoffeSTores(latLong, 15);
    dispatch(getCoffeeStores(fetchedStores));
  }, [latLong]);

  const handleOnBannerBtnClick = () => {
    tracLocationHandler();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Shops</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={loading ? "Loading..." : "View Stores Nearby "}
          handleOnBtnClick={handleOnBannerBtnClick}
        />
        {locationErrMsg && ` Somthing went wrong ${locationErrMsg} `}
        <div className={styles.heroImage}>
          <Image src='/static/hero-image.png' width={700} height={400} />
        </div>
        {latLong && (
          <StoresList
            coffeeStores={coffeeStoresData}
            title='Nearby Coffee Stores '
          />
        )}
        <StoresList
          coffeeStores={props.coffeeStores}
          title='Toronto Coffee Stores '
        />
      </main>
    </div>
  );
}
